# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Park.create([
  {
  full_name: "Abraham Lincoln Birthplace National Historical Park",
  description: "For over a century people from around the world have come to rural Central Kentucky to honor the humble beginnings of our 16th president, Abraham Lincoln. His early life on Kentucky's frontier shaped his character and prepared him to lead the nation through Civil War. The country's first memorial to Lincoln, built with donations from young and old, enshrines the symbolic birthplace cabin.",
  latitude: "37.5858662",
  longitude: "-85.67330523",
  lat_long: "lat:37.5858662, long:-85.67330523",
  state: "KY",
  phone: "270-358-3137",
  email: "ABLI_Administration@nps.gov",
  directions: "The Birthplace Unit of the park is located approximately 2 miles south of the town of Hodgenville on U.S. Highway 31E South. The Boyhood Home Unit at Knob Creek is located approximately 10 miles northeast of the Birthplace Unit of the park.",
  weather: "There are four distinct seasons in Central Kentucky. However, temperature and weather conditions can vary widely within those seasons. Spring and Fall are generally pleasant with frequent rain showers. Summer is usually hot and humid. Winter is moderately cold with mixed precipitation.",
  name: "Abraham Lincoln Birthplace",
  park_type: "National Historical Park"
  },
  {
    full_name: "Acadia National Park",
    description: "Acadia National Park protects the natural beauty of the highest rocky headlands along the Atlantic coastline of the United States, an abundance of habitats, and a rich cultural heritage. At 3.5 million visits a year, it's one of the top 10 most-visited national parks in the United States. Visitors enjoy 27 miles of historic motor roads, 158 miles of hiking trails, and 45 miles of carriage roads.",
    latitude: "44.409286",
    longitude: "-68.247501",
    lat_long: "lat:44.409286, long:-68.247501",
    state: "ME",
    phone: "207-288-3338",
    email: "acadia_information@nps.gov",
    directions: "From Boston take I-95 north to Augusta, Maine, then Route 3 east to Ellsworth, and on to Mount Desert Island. For an alternate route, continue on I-95 north to Bangor, Maine, then take I-395 to U.S. Route 1A east to Ellsworth. In Ellsworth, take Route 3 to Mount Desert Island.",
    weather: "Located on Mount Desert Island in Maine, Acadia experiences all four seasons. Summer temperatures range from 45-90F (7-30C). Fall temperatures range from 30-70F (-1-21C). Typically the first frost is in mid-October and first snowfall begins in November and can continue through April with an average accumulation of 73 inches (185 cm). Winter temperatures range from 14-35F (-10 - 2C). Spring temperatures range from 30-70F (-1-21C).",
    name: "Acadia",
    park_type: "National Park"
  },
  {
    full_name: "Adams National Historical Park",
    description: "From the sweet little farm at the foot of Penn’s Hill to the gentleman’s country estate at Peace field, Adams National Historical Park is the story of “heroes, statesman, philosophers … and learned women” whose ideas and actions helped to transform thirteen disparate colonies into one united nation.",
    latitude: "42.2553961",
    longitude: "-71.01160356",
    lat_long: "lat:42.2553961, long:-71.01160356",
    state: "MA",
    phone: "617-770-1175",
    email: "ADAM_Visitor_Center@nps.gov",
    directions: "Traveling on U.S. Interstate 93, take exit 7 - Route 3 South to Braintree and Cape Cod. Take the first exit off Route 3 south - exit 19 - and follow signs toward Quincy Center. Continue straight on Burgin Parkway through six traffic lights. At the seventh traffic light, turn right onto Dimmock Street. Follow Dimmock Street one block and turn right onto Hancock Street. The National Park Service Visitor Center, located at 1250 Hancock Street on your left. Validated parking is in the garage to the rear.",
    weather: "Be prepared for hot, humid weather. The historic homes are not air conditioned. While the visitor center remains open all year, the historic homes are closed from November 1 through April 30.",
    name: "Adams",
    park_type: "National Historical Park"
  },
  {
    full_name: "African American Civil War Memorial",
    description: "Over 200,000 African-American soldiers and sailors served in the U.S. Army and Navy during the Civil War. Their service helped to end the war and free over four million slaves. The African American Civil War Memorial honors their service and sacrifice.",
    latitude: "38.9166",
    longitude: "-77.026",
    lat_long: "lat:38.9166, long:-77.026",
    state: "DC",
    phone: "202-426-6841",
    email: "national_mall@nps.gov",
    directions: "The memorial is located at the corner of Vermont Avenue, 10th St, and U Street NW, near the U Street/African-American Civil War Memorial/Cardozo Metro Station.",
    weather: "Washington DC gets to see all four seasons. Humidity will make the temps feel hotter in summer and colder in winter. Spring (March - May) Temp: Average high is 65.5 degrees with a low of 46.5 degrees Summer (June - August) Temp: Average high is 86 degrees with a low of 68.5 degrees Fall (September - November) Temp: Average high is 68 degrees with a low of 51.5 degrees Winter (December - February) Temp: Average high is 45 degrees with a low of 30 degrees.",
    name: "African American Civil War Memorial",
    park_type: "Other"
  },
  {
    full_name: "African Burial Ground National Monument",
    description: "African Burial Ground is the oldest and largest known excavated burial ground in North America for both free and enslaved Africans. It protects the historic role slavery played in building New York",
    latitude: "40.71452681",
    longitude: "-74.00447358",
    lat_long: "lat:40.71452681, long:-74.00447358",
    state: "NY",
    phone: "212-238-4367",
    email: "african_burial_ground@nps.gov",
    directions: "The African Burial Ground National Monument is located on the first floor of the Ted Weiss Federal Building located at 290 Broadway in Lower Manhattan; close to Foley Square and just north of City Hall. Our visitor center is located mid-block on Broadway between the cross streets of Duane Street and Reade Streets.",
    weather: "No weather information at this time.",
    name: "African Burial Ground",
    park_type: "National Monument"
  },
  {
    full_name: "Agate Fossil Beds National Monument",
    description: "During the 1890s, scientists rediscovered what the Lakota Sioux already knew—bones preserved in one of the world's most significant Miocene Epoch mammal sites. Yet, this place called 'Agate' is a landscape that reflects many influences—from early animals roaming the valleys and hills, to tribal nations calling the High Plains home, to explorers passing through or settling in the American West.",
    latitude: "42.42170419",
    longitude: "-103.753886",
    lat_long: "lat:42.42170419, long:-103.753886",
    state: "NE",
    phone: "308-665-4113",
    email: "agfo_ranger_activities@nps.gov",
    directions: "If traveling east or west on U.S. Highway 20 go 22 miles south of Harrison, NE on State Hwy 29 then 3 miles east on River Road (paved) If traveling east or west on U.S. Highway 26 go 34 miles north of Mitchell, NE on State Hwy 29 then 3 miles east on River Road (paved). Also accessible from State Hwy 71, 25 miles on unpaved River Road.",
    weather: "Summers can be very warm, high 90's to 100 with the possibility of thunderstorms late afternoons. Winter temperatures can dip as low as -20 with some snow and wind. Heaviest snows can be expected in late Spring.",
    name: "Agate Fossil Beds",
    park_type: "National Monument"
  },
  {
    full_name: "Ala Kahakai National Historic Trail",
    description: "Established in 2000 to preserve, protect and interpret traditional Native Hawaiian culture and natural resources, Ala Kahakai National Historic Trail is a 175 mile corridor encompassing a network of culturally and historically significant trails. This \"trail by the sea\" traverses wahi pana (storied landscapes), ancient Hawaiian sites and over 200 ahupuaʻa (traditional land divisions). Connect now!",
    latitude: "19.1446681090248",
    longitude: "-155.890734293795",
    lat_long: "lat:19.1446681090248, long:-155.890734293795",
    state: "HI",
    phone: "8083266012",
    email: "aric_arakaki@nps.gov",
    directions: "The trail can be unofficially accessed through sections within the four National Parks on the Island of Hawai'i including Hawaii Volcanoes National Park, Pu'uhonua o Honaunau National Historical Park, Kaloko-Honokohau National Historical Park and Pu'ukohola National Historic Site. Otherwise, the section of the Ala Kahakai Trail under Hawaii State Na Ala Hele jurisdiction is open for public use.",
    weather: "Island weather is unpredictable. Visitors should be prepared for rain and wear layers of clothing to ensure their comfort while exploring the park.",
    name: "Ala Kahakai",
    park_type: "National Historic Trail"
  },
  {
    full_name: "Alagnak Wild River",
    description: "The headwaters of Alagnak Wild River lie within the rugged Aleutian Range of neighboring Katmai National Park and Preserve. Meandering west towards Bristol Bay and the Bering Sea, the Alagnak traverses the beautiful Alaska Peninsula, providing an unparalleled opportunity to experience the unique wilderness, wildlife, and cultural heritage of southwest Alaska.",
    latitude: "59.05180188",
    longitude: "-156.112002",
    lat_long: "lat:59.05180188, long:-156.112002",
    state: "AK",
    phone: "907-246-3305",
    email: "KATM_Visitor_Information@nps.gov",
    directions: "Alagnak Wild River is located in a remote part of the Alaska Peninsula, about 290 miles southwest of Anchorage. Access is by boat or small floatplane.",
    weather: "Located between the stormy north Pacific Ocean and the even stormier Bering Sea, the Alagnak Wild River is often a battleground between weather systems. When you visit, be prepared to encounter all types of weather.  On average, wet and cool conditions predominate in spring, summer, and fall. Winters are drier and colder.",
    name: "Alagnak",
    park_type: "Wild River"
  },
  {
    full_name: "Alaska Public Lands",
    description: "Alaska’s parks, forests, and refuges are rich and varied. The Alaska Public Lands Information Centers help visitors and residents to have meaningful, safe, enjoyable experiences on public lands, and encourages them to sustain the natural and cultural resources of Alaska. These centers provide trip-planning, interpretation, and education for all ages.",
    latitude: "61.2188",
    longitude: "-149.894536",
    lat_long: "lat:61.2188, long:-149.894536",
    state: "AK",
    phone: "907-644-3661",
    email: "anch_web_mail@nps.gov",
    directions: "Anchorage APLIC is located in downtown Anchorage on 4th Avenue, in the Federal Building. Fairbanks APLIC is located in downtown Fairbanks on the corner of Dunkel Street and Wendell Avenue, near the Chena River.",
    weather: "Visitors center is located inside the Federal Building and weather conditions are seasonal conditions of the Anchorage area, outside the facility.",
    name: "Alaska Public Lands",
    park_type: "Other"
  },
  {
    full_name: "Alcatraz Island",
    description: "Alcatraz reveals stories of American incarceration, justice, and our common humanity. This small island was once a fort, a military prison, and a maximum security federal penitentiary. In 1969, the Indians of All Tribes occupied Alcatraz for 19 months in the name of freedom and Native American civil rights. We invite you to explore Alcatraz's complex history and natural beauty.",
    latitude: "37.82676234",
    longitude: "-122.4230206",
    lat_long: "lat:37.82676234, long:-122.4230206",
    state: "CA",
    phone: "415-561-4900",
    email: "goga_alca_socialmedia@nps.gov",
    directions: "The Alcatraz Ferry Terminal is located on The Embarcadero near the intersection of Bay Street at Pier 33.",
    weather: "The climate on Alcatraz is unpredictable and can change suddenly. Cold, foggy mornings may give way to sunny afternoons, which in turn can shift quickly back to more fog and blustery winds. The most pleasant weather usually occurs in spring and fall. Summers tend to be cool and foggy, winter is our rainy season. Temperatures on Alcatraz seldom rise above 75°F (24°C) or fall below 38°",
    name: "Alcatraz Island",
    park_type: "Other"
  },
  {
    full_name: "Aleutian Islands World War II National Historic Area",
    description: "During World War II the remote Aleutian Islands, home to the Unangax̂ (Aleut) people for over 8,000 years, became a fiercely contested battleground in the Pacific. This thousand-mile-long archipelago saw invasion by Japanese forces, the occupation of two islands; a mass relocation of Unangax̂ civilians; a 15-month air war; and one of the deadliest battles in the Pacific Theater.",
    latitude: "53.9143",
    longitude: "-166.5197",
    lat_long: "lat:53.9143, long:-166.5197",
    state: "AK",
    phone: "907-644-3472",
    email: "rachel_mason@nps.gov",
    directions: "The park is located on Amaknak Island in the Aleutian Island chain. The island is located 800 miles west of Anchorage. The island can be reached by commercial or charter air flights from Anchorage. Commercial flights to Unalaska include Pen Air and Alaska Airlines. The Alaska Marine Highway is a ferry service that is operated by the state that can be used to reach the island. The Aleutian World War II Visitor Center is located at the Unalaska airport.",
    weather: "The Aleutian Islands are known for unpredictable and stormy weather. Rain, fog, and wind are common. Dress warmly and carry rain gear even in summer. Summer temperatures range from 45 to 65 degrees F. Early summer and fall often have clear sunny days with spectacular views of the surrounding volcanoes.",
    name: "Aleutian Islands World War II",
    park_type: "National Historic Area"
  },
  {
    full_name: "Alibates Flint Quarries National Monument",
    description: "13,000 years ago, this site was well-known by mammoth hunters as a source of flint for tools. Centuries passed but the colorful flint never lost its value and usefulness in the Texas Panhandle. Gain a sense of how integral this site was to the survival, commerce and culture of the High Plains. Visit Alibates Flint Quarries to see the many colors of the beautiful Alibates Flint.",
    latitude: "35.5819662",
    longitude: "-101.6717008",
    lat_long: "lat:35.5819662, long:-101.6717008",
    state: "TX",
    phone: "806-857-6680",
    email: "lamr_interpretation@nps.gov",
    directions: "Alibates Flint Quarries is located approximately 35 miles north of Amarillo, Texas. From I-40 in Amarillo, take Lakeside exit north towards Lake Meredith National Recreation Area. Exit on TX 136 north towards Borger. After about 30 miles, turn west from TX 136 onto Cas Johnson Road. Park Service signs will be visible. Proceed approximately 3 miles to \"Y\" intersection and bear to right. Go northwest approximately 2 miles to the Alibates Flint Quarries National Monument Visitor Center.",
    weather: "The Texas Panhandle experiences a wide variety of weather conditions throughout the year. Winters are cold and windy, and summers are hot and dry. It is usually a good idea to bring a jacket with you if you are planning on hiking to the quarries with a ranger because the mesa gets very windy, even in the summer.",
    name: "Alibates Flint Quarries",
    park_type: "National Monument"
  },
  {
    full_name: "Allegheny Portage Railroad National Historic Site",
    description: "The first railroad to circumvent the Allegheny Mountains, the Allegheny Portage Railroad was the finishing piece of the Pennsylvania Mainline Canal. 'The Portage,' opened in 1834, marking the first time that there was one, direct route between Philadelphia and Pittsburgh. All things to all people, it served merchants, passengers, slaves in pursuit of freedom, and soldiers from the Mexican War.",
    latitude: "40.42977467",
    longitude: "-78.57431622",
    lat_long: "lat:40.42977467, long:-78.57431622",
    state: "PA",
    phone: "814-886-6150",
    email: "alpo_interpretation@nps.gov",
    directions: "The park is located just off U.S. Route 22 approximately 12 miles west of Altoona and 10 miles east of Ebensburg. Take the Gallitzin Exit and turn right, following the signs. Visitors prior to 1992 accessed the park in other ways, but the GALLITZIN EXIT of US Route 22 is now the way to access the visitor center and historic area.",
    weather: "The park is located in Cambria County, PA, and is at the summit of the Allegheny Mountains. Therefore, the park often takes on winter extremes. If planning on traveling from a long distance, please contact the park beforehand to ensure that the facilities are open. Please consult weather forecasts to ensure conditions are safe to travel in. Spring, summer, and fall are generally uneventful, but severe thunderstorms can occur.",
    name: "Allegheny Portage Railroad",
    park_type: "National Historic Site"
  },
  {
    full_name: "American Memorial Park",
    description: "American Memorial Park honors the American and Marianas people who gave their lives during the Marianas Campaign of World War II. At the park, memorials stand in tribute to the courage and sacrifice of the US Servicemen and Chamorro and Carolinian civilians who were killed in the battles between the United States and Japan that took place on Saipan, Tinian, and the Philippine Sea in 1944.",
    latitude: "15.21680033",
    longitude: "145.7231096",
    lat_long: "lat:15.21680033, long:145.7231096",
    state: "MP",
    phone: "670-234-7207",
    email: "AMME_Administration@nps.gov",
    directions: "The park is centrally located along the western shoreline of Saipan, adjacent to downtown Garapan. From airport, proceed north on Airport Road (Tun Herman Pan Highway) until the road ends at Monsignor Guerrero Road (Highway 16). Turn left and continue until the road ends at Beach Road. Turn right until the road ends at the American Memorial Park Mall. Turn left onto Micro Beach Road. The parking lot is on the right.",
    weather: "The temperature varies from 75°F to 88°F and is rarely below 73°F or above 90°F.The climate is tropical, hot and humid throughout the year, with a relatively cool and dry season from December to June, and a warmer and rainy season from July to November. The temperatures are stable throughout the year.",
    name: "American Memorial Park",
    park_type: "Other"
  },
  {
    full_name: "Amistad National Recreation Area",
    description: "An oasis in the desert, Amistad National Recreation Area consists of the US portion of the International Amistad Reservoir. Amistad, whose name comes from the Spanish word meaning friendship, is best known for excellent water-based recreation, camping, hiking, rock art viewing, and its rich cultural history. Amistad is also home to a wide variety of plant and animal life above and below the water.",
    latitude: "29.53539777",
    longitude: "-101.075821",
    lat_long: "lat:29.53539777, long:-101.075821",
    state: "TX",
    phone: "830-775-7491",
    email: "amis_interpretation@nps.gov",
    directions: "Six miles west of the HWY 90 and 277 North intersection at 10477 Highway 90 West.",
    weather: "Weather in Southwest Texas can change in a matter of minutes. It is best to check the local weather report. Amistad National Recreation Area usually has hot summers and mild winters. For more information, please visit our Weather page at https://www.nps.gov/amis/planyourvisit/weather.htm.",
    name: "Amistad",
    park_type: "National Recreation Area"
  },
  {
    full_name: "Anacostia Park",
    description: "Welcome to Anacostia Park, your neighborhood national park in the heart of Washington, DC! Enjoy exercise along the river trail or relax by the water, Anacostia Park is a breath of fresh air and a space to unwind amid a bustling city.",
    latitude: "38.8782",
    longitude: "-76.9703",
    lat_long: "lat:38.8782, long:-76.9703",
    state: "DC",
    phone: "202-472-3884",
    email: "nace_superintendent@nps.gov",
    directions: "Anacostia Park is located in South East Washington DC running parallel to the Anacostia river. The park can be accessed from the South Capitol bridge over the Anacostia river across from the Nationals baseball stadium. You could also enter from Pennsylvania avenue over the Anacostia river as well.",
    weather: "Spring brings mild temperatures and a light breeze along with springtime flower blooms. Summer can be hot and humid. Fall cools down and changing of the seasons brings changing of the colors in leaves. Winter gets cold and temperatures may drop below freezing.",
    name: "Anacostia Park",
    park_type: "Other"
  },
  {
    full_name: "Andersonville National Historic Site",
    description: "The Camp Sumter military prison at Andersonville was one of the largest Confederate military prisons during the Civil War. During the 14 months the prison existed, more than 45,000 Union soldiers were confined here. Of these, almost 13,000 died here. Today, Andersonville National Historic Site is a memorial to all American prisoners of war throughout the nation's history.",
    latitude: "32.19831758",
    longitude: "-84.12988898",
    lat_long: "lat:32.19831758, long:-84.12988898",
    state: "GA",
    phone: "229-924-0343",
    email: "ande_information@nps.gov",
    directions: "Andersonville National Historic Site is located in southwest Georgia. The park is approximately 12 miles north of Americus and 11 miles south of Montezuma on GA-49.",
    weather: "Summer temperatures reach highs in the 80s-90s and high humidity. Winter temperatures tend to be in the 40s and below. Snow can occur but is rare. Average annual precipitation is 46.24 inches and is fairly evenly distributed throughout the year. The National Prisoner of War Museum is maintained at a cool temperature to help preserve artifacts; dressing in layers is recommended.",
    name: "Andersonville",
    park_type: "National Historic Site"
  },
  {
    full_name: "Andrew Johnson National Historic Site",
    description: "Andrew Johnson's complex presidency (1865-69) illustrates the Constitution at work following the Civil War. As the President and Congress disagreed on Reconstruction methods, the Constitution served as their guide on balance of powers, vetoes, and impeachment. In the end, it evolved as a living document with pivotal amendments on freedom, citizenship, and voting rights - topics still vital today.",
    latitude: "36.15624509",
    longitude: "-82.83709021",
    lat_long: "lat:36.15624509, long:-82.83709021",
    state: "TN",
    phone: "423-638-3551",
    email: "anjo_information@nps.gov",
    directions: "GPS The GPS setting for Andrew Johnson NHS may be listed as 121 Monument Ave, which is the park HQ in the National Cemetery. To arrive at the Visitor Center, use 101 North College Street, Greeneville, TN. Plane The closest airport is the Tri-Cities Regional Airport, 43 miles NE of Greeneville. From the airport, take I-81 South to exit 36 and follow the signs to Greeneville. Car From I-81S take exit 36 to Rt. 172 south to Greeneville. From I-81N take exit 23 to Rt. 11E north to Greeneville.",
    weather: "There are four distinct seasons in East Tennessee, but temperature and weather conditions can vary widely within those seasons. Spring and Fall are generally pleasant with frequent rain showers. Summer and Winter ranges can be extreme. The President's Homestead is not climate controlled and may be closed at times during excessive highs or lows in the summer and winter.",
    name: "Andrew Johnson",
    park_type: "National Historic Site"
  },
  {
    full_name: "Aniakchak National Monument & Preserve",
    description: "Given its remote location and challenging weather conditions, Aniakchak is one of the most wild and least visited places in the National Park System. This landscape is a vibrant reminder of Alaska's location in the volcanically active \"Ring of Fire,\" as it is home to an impressive six mile (10 km) wide, 2,500 ft (762 m) deep caldera formed during a massive volcanic eruption 3,500 years ago.",
    latitude: "56.85317675",
    longitude: "-157.5544362",
    lat_long: "lat:56.85317675, long:-157.5544362",
    state: "AK",
    phone: "9072463305",
    email: "KATM_Visitor_Information@nps.gov",
    directions: "Located on the Alaska Peninsula, 450 miles southwest of Anchorage, Aniakchak National Monument and Preserve is inaccessible by road. Notoriously bad weather makes access to Aniakchak unpredictable. Drop-offs and/or pick-ups may be significantly delayed.",
    weather: "When you visit, be prepared to encounter all types of weather. On average, wet and cool conditions predominate in spring, summer, and fall. Strong winds can delay the departure and arrival of boats and floatplanes.",
    name: "Aniakchak",
    park_type: "National Monument & Preserve"
  },
  {
    full_name: "Antietam National Battlefield",
    description: "23,000 soldiers were killed, wounded or missing after twelve hours of savage combat on September 17, 1862. The Battle of Antietam ended the Confederate Army of Northern Virginia's first invasion into the North and led Abraham Lincoln to issue the preliminary Emancipation Proclamation.",
    latitude: "39.46763452",
    longitude: "-77.73828017",
    lat_long: "lat:39.46763452, long:-77.73828017",
    state: "MD",
    phone: "3014325124",
    email: "anti_info@nps.gov",
    directions: "Ten miles south of I-70 on Maryland Route 65",
    weather: "The weather is fairly mild. Summers can be very warm and humid and winters cold and snowy. We have four distinct seasons with the fall and spring being the best times to visit the battlefield.",
    name: "Antietam",
    park_type: "National Battlefield"
  },
  {
    full_name: "Apostle Islands National Lakeshore",
    description: "Imagine that moment, being in that perfect spot as the sun rises, and everything comes into focus. A rocky shoreline suddenly reflects the world around you. Waiting for you among the water, land, forests, and history is that moment. How will the islands inspire you?",
    latitude: "46.96240467",
    longitude: "-90.66045665",
    lat_long: "lat:46.96240467, long:-90.66045665",
    state: "WI",
    phone: "7157793397",
    email: "apis_information@nps.gov",
    directions: "Apostle Islands National Lakeshore features several points of interest with much of it only accessible by water.",
    weather: "Lake Superior is renowned for its cold temperatures, rough seas, fog, and sudden squalls. Boaters and paddlers should monitor marine weather forecasts and be constantly alert to changing conditions. Average daytime high temperatures range from 60 degrees Fahrenheit in May, to the upper 80s in mid-summer, to the mid-60s in September. Average lows vary from 40 degrees in May, to the upper 50s in mid-summer, to 50 degrees in September. Average water temperatures in May and June are only in the 40s.",
    name: "Apostle Islands",
    park_type: "National Lakeshore"
  },
  {
    full_name: "Appalachian National Scenic Trail",
    description: "The Appalachian Trail is a 2,180+ mile long public footpath that traverses the scenic, wooded, pastoral, wild, and culturally resonant lands of the Appalachian Mountains. Conceived in 1921, built by private citizens, and completed in 1937, today the trail is managed by the National Park Service, US Forest Service, Appalachian Trail Conservancy, numerous state agencies and thousands of volunteers.",
    latitude: "40.41029575",
    longitude: "-76.4337548",
    lat_long: "lat:40.41029575, long:-76.4337548",
    state: "CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV",
    phone: "304-535-6278",
    email: "None",
    directions: "There are many points of access along the Appalachian Trail, whether it is by car, train, bus or plane. For more detailed directions, please refer to the \"Directions\" section of our park webpage.",
    weather: "It is your responsibility to be prepared for all weather conditions, including extreme and unexpected weather changes year-round. As the trail runs from Georgia to Maine there will be different weather conditions depending on your location. For weather along specific sections of the trail and at specific shelters, please refer to: http://www.atweather.org/",
    name: "Appalachian",
    park_type: "National Scenic Trail"
  },
  {
    full_name: "Appomattox Court House National Historical Park",
    description: "On April 9, 1865, the surrender of the Army of Northern Virginia in the McLean House in the village of Appomattox Court House, Virginia signaled the end of the nation's largest war. Two important questions about its future were answered. Could the nation survive a civil war intact, and would that nation exist without slavery? The answer to both was yes and a new nation was born.",
    latitude: "37.38022164",
    longitude: "-78.79856982",
    lat_long: "lat:37.38022164, long:-78.79856982",
    state: "VA",
    phone: "434-352-8987",
    email: "APCO_SocialMedia@nps.gov",
    directions: "Appomattox Court House NHP is located 3 miles east of U.S. Highway 460, and 3 miles east of the modern town of Appomattox, Virginia along Rt. 24.",
    weather: "The park may close due to emergency weather conditions (typically snow or ice). For updated information about possible closure or altered hours due to weather, please call 434-352-8987 ext. 245.",
    name: "Appomattox Court House",
    park_type: "National Historical Park"
  },
  {
    full_name: "Arches National Park",
    description: "Visit Arches to discover a landscape of contrasting colors, land forms, and textures unlike any other in the world. The park has over 2,000 natural stone arches and hundreds of soaring pinnacles, massive rock fins, and giant balanced rocks. This red-rock wonderland will amaze you with its formations, refresh you with its trails, and inspire you with its sunsets.",
    latitude: "38.72261844",
    longitude: "-109.5863666",
    lat_long: "lat:38.72261844, long:-109.5863666",
    state: "UT",
    phone: "435-719-2299",
    email: "archinfo@nps.gov",
    directions: "Arches National Park is located in southeast Utah, five miles north of Moab on US 191. From Moab, Utah, drive five miles north on Main Street/US 191. Turn right at the stoplight. From Interstate 70, take exit 182 (Crescent Junction), then drive south 28 miles on US 191. Turn left at the stoplight.",
    weather: "Arches is part of the Colorado Plateau, a \"high desert\" region that experiences wide temperature fluctuations, sometimes over 40 degrees in a single day. The temperate (and most popular) seasons are spring (April-May) and fall (mid-September-October), when daytime highs average 60 to 80 F and lows average 30 to 50 F. Summer temperatures often exceed 100 F, making strenuous exercise difficult. Winters are cold, with highs averaging 30 to 50 F, and lows averaging 0 to 20 F.",
    name: "Arches",
    park_type: "National Park"
  },
  {
    full_name: "Arkansas Post National Memorial",
    description: "Located at the confluence of two rivers, Arkansas Post has served as a gathering place for many cultures throughout human history - it represents cultural cooperation, conflict, synthesis, and diversity.",
    latitude: "34.00389998",
    longitude: "-91.30837178",
    lat_long: "lat:34.00389998, long:-91.30837178",
    state: "AR",
    phone: "870-548-2207",
    email: "teresa_donaldson@nps.gov",
    directions: "Arkansas Post National Memorial is located in southeastern Arkansas. The entrance to the park is on Arkansas Hwy 169, seven miles south of Gillett, via US Hwy 165 (The Great River Road), and about 20 miles northeast of Dumas, via US 165.",
    weather: "Arkansas shares the same climate classification as the rest of the southeastern United States: humid subtropical. This type of climate features relatively mild winters and hot, steamy summers.",
    name: "Arkansas Post",
    park_type: "National Memorial"
  },
  {
    full_name: "Arlington House, The Robert E. Lee Memorial",
    description: "Arlington House is the nation’s memorial to Robert E. Lee. It honors him for specific reasons, including his role in promoting peace and reunion after the Civil War. In a larger sense it exists as a place of study and contemplation of the meaning of some of the most difficult aspects of American History: military service; sacrifice; citizenship; duty; loyalty; slavery and freedom.",
    latitude: "38.8822021484375",
    longitude: "-77.0734786987305",
    lat_long: "lat:38.8822021484375, long:-77.0734786987305",
    state: "VA",
    phone: "7032351530",
    email: "gwmp_superintendent@nps.gov",
    directions: "Public Transportation: The Memorial is accessible by the Blue Line of the Metro subway system. The Arlington Cemetery subway station is near the Visitor Center for the cemetery. Car: Arlington House is located inside Arlington National Cemetery. If you plan to come in a vehicle, the nearest parking is in the Arlington National Cemetery parking garage. From the entrance and Welcome Center at Arlington National Cemetery, one can walk up the hill to Arlington House (approximately 15 minutes-steep)",
    weather: "Summers on the parkway are generally hot and humid, with daytime highs frequently above 90 degrees Fahrenheit and scattered afternoon thunderstorms. Please carry water while participating in physical activity and be prepared to take shelter from lightning. Winters on the parkway are generally cold, with nighttime lows frequently near freezing and occasional snowfall. Please be alert for snowplows and icy spots on roadways. Weather during spring and fall is generally moderate, but can change quickly.",
    name: "Arlington House, The Robert E. Lee Memorial",
    park_type: "Other"
  },
  {
    full_name: "Assateague Island National Seashore",
    description: "Want to live on the edge? Visit a place recreated each day by ocean wind and waves. Life on Assateague Island has adapted to an existence on the move. Explore sandy beaches, salt marshes, maritime forests and coastal bays. Rest, relax, recreate and enjoy some time on the edge of the continent.",
    latitude: "38.05593172",
    longitude: "-75.24524611",
    lat_long: "lat:38.05593172, long:-75.24524611",
    state: "MD,VA",
    phone: "410-641-1441",
    email: "asis_information@nps.gov",
    directions: "There are two entrances to Assateague Island National Seashore. Assateague's north entrance is at the end of Route 611, eight miles south of Ocean City, MD. The south entrance is at the end of Route 175, two miles east of Chincoteague, VA. There is no vehicle access between the two entrances on Assateague Island. Vehicles must return to the mainland to access either the north or south entrance.",
    weather: "Spring: Often windy and cool with lows in the 40's and highs in the 60's. Summer: Hot and humid with lows in the 60's and highs in the 80's. Fall: Warm with lows in the 50's and highs in the 70's. Winter: Damp cold and often windy. Lows in the 20's, highs in the 40's.",
    name: "Assateague Island",
    park_type: "National Seashore"
  },
  {
    full_name: "Aztec Ruins National Monument",
    description: "Pueblo people describe this site as part of their migration journey. Today you can follow their ancient passageways to a distant time. Explore a 900-year old ancestral Pueblo Great House of over 400 masonry rooms. Look up and see original timbers holding up the roof. Search for the fingerprints of ancient workers in the mortar. Listen for an echo of ritual drums in the reconstructed Great Kiva.",
    latitude: "36.83682216",
    longitude: "-107.9999245",
    lat_long: "lat:36.83682216, long:-107.9999245",
    state: "NM",
    phone: "505-334-6174",
    email: "azru_information@nps.gov",
    directions: "From Albuquerque/Bloomfield, NM: Follow Hwy 550 north into Aztec, turn left onto Highway 516, drive 3/4 mile, then turn right onto Ruins Road. Follow Ruins Road 1/2 mile to the monument. From Durango, CO: Follow Hwy 550 south into Aztec, where it will become 516. Turn right onto Ruins Road. Follow Ruins Road 1/2 mile to the monument. From Farmington, NM Follow Highway 516 east into Aztec. 1/4 mile past Lightplant Road, turn left onto Ruins Road. Follow Ruins Road 1/2 mile to the monument.",
    weather: "Summer High temperatures range between 80°F and 99°F degrees with a few days over 100°F. Afternoon thunderstorms usually cool things down in late July and August. Fall Usually pleasant, with mild days and crisp nights. Winter Daytime temperatures range between 20°F and 50°F with cold nights that can reach 0°F. Snow is periodic, but accumulations are typically only 1-2 inches. Spring Weather is especially unpredictable: it can be windy, cold, and wet, or still, warm, and dry.",
    name: "Aztec Ruins",
    park_type: "National Monument"
  },
  {
    full_name: "Badlands National Park",
    description: "The rugged beauty of the Badlands draws visitors from around the world. These striking geologic deposits contain one of the world’s richest fossil beds. Ancient horses and rhinos once roamed here. The park’s 244,000 acres protect an expanse of mixed-grass prairie where bison, bighorn sheep, prairie dogs, and black-footed ferrets live today.",
    latitude: "43.68584846",
    longitude: "-102.482942",
    lat_long: "lat:43.68584846, long:-102.482942",
    state: "SD",
    phone: "605-433-5361",
    email: "badl_information@nps.gov",
    directions: "Badlands National Park is located 75 miles east of Rapid City, South Dakota. Physical Addresses for GPS* Park Headquarters: 25216 Ben Reifel Road, Interior, SD 57750. Northeast Entrance (I-90, Exit 131): 21020 SD Hwy 240, Interior, SD 57750. Pinnacles Entrance (I-90, Exit 110): 24240 Hwy 240, Wall, SD 57790. Interior Entrance: 20640 SD Hwy 377, Interior, SD 57750.",
    weather: "The Badlands weather is variable and unpredictable with temperature extremes ranging from 116° F to -40° F. Summers are hot and dry with occasional violent thunderstorms. Hailstorms and occasional tornadoes can descend on the Badlands with sudden fury. Winters are typically cold with 12 to 24 inches of total snowfall.",
    name: "Badlands",
    park_type: "National Park"
  },
  {
    full_name: "Baltimore-Washington Parkway",
    description: "This 29-mile highway connects Baltimore, MD and Washington, D.C. The parkway has carried visitors to and from the capital city since 1954.",
    latitude: "39.02604289",
    longitude: "-76.85410921",
    lat_long: "lat:39.02604289, long:-76.85410921",
    state: "MD",
    phone: "301-344-3948",
    email: "matthew_carroll@nps.gov",
    directions: "This 29-mile highway connects Baltimore, MD and Washington, D.C",
    weather: "The Washington, D.C. area has a four-season Mid-Atlantic climate. Summertime is warm and humid, while winter can be cold and snowy. Spring: During these months of transition, the weather can alternate from warm, humid air coming from the south to cold, dry air coming from the northwest. Be prepared for changing conditions. Summer: The warmest months are June, July, and August, with average highs in the 80s (~31 ?) combined with high humidity. Temperatures often climb into the 90s (~34?).",
    name: "Baltimore-Washington Parkway",
    park_type: "Other"
  },
  {
    full_name: "Bandelier National Monument",
    description: "Bandelier National Monument protects over 33,000 acres of rugged but beautiful canyon and mesa country as well as evidence of a human presence here going back over 11,000 years. Petroglyphs, dwellings carved into the soft rock cliffs, and standing masonry walls pay tribute to the early days of a culture that still survives in the surrounding communities.",
    latitude: "35.77898596",
    longitude: "-106.3317124",
    lat_long: "lat:35.77898596, long:-106.3317124",
    state: "NM",
    phone: "505-672-3861",
    email: "band_visitor_center@nps.gov",
    directions: "From NM285 US84 in Pojaque NM. West on NM502, West on NM4 to White rock. Then 12 miles to the monument entrance on the south side of the road.",
    weather: "Spring daytime temperatures in the 70's can be followed by a snow storm with wet heavy snow and daytime temperatures in the 40's. Summer s dry with June usually being the hottest month of the year. Days in July, August and September often end with thunderstorms that can drop heavy localized rain and are often accompanied by lightning. Autumn weather is usually sunny with turquoise blue skies and warm (but not hot) days and cool nights. Winter average snowfall 25\". Snow and ice can close trails and roads.",
    name: "Bandelier",
    park_type: "National Monument"
  },
  {
    full_name: "Belmont-Paul Women's Equality National Monument",
    description: "Home to the National Woman's Party for more than 90 years, this was the epicenter of the struggle for women's rights. From this house in the shadow of the U.S. Capitol and Supreme Court, Alice Paul and the NWP developed innovative strategies and tactics to advocate for the Equal Rights Amendment and equality for women. President Barack Obama designated the national monument on April 12, 2016.",
    latitude: "38.89231541",
    longitude: "-77.00381882",
    lat_long: "lat:38.89231541, long:-77.00381882",
    state: "DC",
    phone: "202-543-2240",
    email: "bepa_info@nps.gov",
    directions: "The Belmont-Paul Women's Equality NM is located on Capitol Hill at the corner of Constitution Avenue and 2nd Street, NE, next to the Hart Senate Office building. It is a free-standing, federal style brick house surrounded by a black cast-iron fence. The entrance for museum tours and the museum shop is located on 2nd Street with the lift accessible entrance located to the side of the museum next to the Hart Senate Office Building. The doors facing Constitution Avenue are not entrances.",
    weather: "Washington DC gets to see all four seasons. Humidity will make the temps feel hotter in summer and colder in winter. Spring (March - May) Temp: Average high is 65.5 degrees with a low of 46.5 degrees Summer (June - August) Temp: Average high is 86 degrees with a low of 68.5 degrees Fall (September - November) Temp: Average high is 68 degrees with a low of 51.5 degrees Winter (December - February) Temp: Average high is 45 degrees with a low of 30 degrees.",
    name: "Belmont-Paul Women's Equality",
    park_type: "National Monument"
  },
  {
    full_name: "Bent's Old Fort National Historic Site",
    description: "Bent's Old Fort National Historic Site features a reconstructed 1840s adobe fur trading post on the mountain branch of the Santa Fe Trail where traders, trappers, travelers, and the Cheyenne and Arapaho tribes came together in peaceful terms for trade. Today, living historians recreate the sights, sounds, and smells of the past with guided tours, demonstrations and special events.",
    latitude: "38.03977546",
    longitude: "-103.4266499",
    lat_long: "lat:38.03977546, long:-103.426649",
    state: "CO",
    phone: "719-383-5010",
    email: "beol_interpretation@nps.gov",
    directions: "The park is accessed via U.S. Highway 50 and Highway 194. From La Junta, Colorado on U.S. Highway 50, take Colorado Highway 109 north 1 mile to Colorado Highway 194, then east on Colorado Highway 194 six miles to the fort. From Las Animas, Colorado, on U.S. Highway 50, take Colorado Highway 194 west 13 miles. Set your GPS to 35110 State Highway 194 E., La Junta, CO.",
    weather: "Summer temperatures are are often in the high 90s and low 100s. Weather is generally fair in the fall and spring. Winter temperatures can be below freezing. Most of the fort is unheated and does not have modern cooling systems, so dress accordingly.",
    name: "Bent's Old Fort",
    park_type: "National Historic Site"
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  },
  {
    full_name: "",
    description: "",
    latitude: "",
    longitude: "",
    lat_long: "",
    state: "",
    phone: "",
    email: "",
    directions: "",
    weather: "",
    name: "",
    park_type: ""
  }

])